#!/usr/bin/env python
# $Id: remap_names.py 1340 2010-09-15 11:54:11Z mcolosimo $
"""
This adds back the names to the tree generated by panjo after it is turned into a phyloxml format from a nwk

@author: Marc E. Colosimo
@copyright: The MITRE Corporation, ALL RIGHTS RESERVED, 2010
@version: $Rev: 1340 $
"""
import sys
import re

nameRE = re.compile(".*<name>(\d+)</name>.*")

names = {}
phylip = open(sys.argv[1])
line = phylip.readline()
# skip header
line = phylip.readline()
cv = 1                      # panjo starts at 1!
while line:
    names["%s" % cv] = line.split(' ')[0]
    cv += 1
    line = phylip.readline()
    
print >>sys.stderr, "Found %d names" % len(names)    

panjo = open(sys.argv[2])    # panjo nwk file that was turned into a phyloxml
for line in panjo:
    mo = nameRE.match(line)
    if mo:
        #print "replacing %s with %s" % (mo.group(1), names[mo.group(1)])
        print line.replace(mo.group(1), names[mo.group(1)])
    else:
        print line
